Name:           perl-Test-Tester
Version:        0.107
Release:        5%{?dist}
Summary:        Ease testing test modules built with Test::Builder
License:        Artistic clarified
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/Test-Tester/
Source0:        http://www.cpan.org/authors/id/F/FD/FDALY/Test-Tester-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(Test::Builder)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
If you have written a test module based on Test::Builder then Test::Tester
allows you to test it with the minimum of effort.

%prep
%setup -q -n Test-Tester-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc ARTISTIC CHANGES README TODO
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Thu Feb 25 2010 Marcela Mašláňová <mmaslano@redhat.com> - 0.107-5
- fix license. It's specified by upstream as Artistic clarified
- Related: rhbz#543948 

* Thu Dec 03 2009 Dennis Gregorovic <dgregor@redhat.com> - 0.107-3.1
- Rebuilt for RHEL 6

* Sun Jul 26 2009 Fedora Release Engineering <rel-eng@lists.fedoraproject.org> - 0.107-3
- Rebuilt for https://fedoraproject.org/wiki/Fedora_12_Mass_Rebuild

* Thu Feb 26 2009 Fedora Release Engineering <rel-eng@lists.fedoraproject.org> - 0.107-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_11_Mass_Rebuild

* Fri May 16 2008 Steven Pritchard <steve@kspei.com> 0.107-1
- Update to 0.107.

* Wed Feb 27 2008 Tom "spot" Callaway <tcallawa@redhat.com> - 0.106-3
- Rebuild for perl 5.10 (again)

* Thu Jan 24 2008 Tom "spot" Callaway <tcallawa@redhat.com> 0.106-2
- rebuild for new perl
- fix license tag

* Tue Sep 18 2007 Steven Pritchard <steve@kspei.com> 0.106-1
- Update to 0.106.
- BR Test::Builder.

* Wed Apr 18 2007 Steven Pritchard <steve@kspei.com> 0.104-2
- BR ExtUtils::MakeMaker.

* Tue Dec 26 2006 Steven Pritchard <steve@kspei.com> 0.104-1
- Update to 0.104.
- Use fixperms macro instead of our own chmod incantation.

* Sat Sep 16 2006 Steven Pritchard <steve@kspei.com> 0.103-2
- Fix find option order.

* Sat Apr 08 2006 Steven Pritchard <steve@kspei.com> 0.103-1
- Specfile autogenerated by cpanspec 1.64.
- Fix License.
